name: Deploy FE to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'shoes-store-app-fe/**'

env:
  TARGET_PATH: 'shoes-store-app-fe'
  EC2_HOST: ${{ secrets.EC2_HOST }}
  SSH_USERNAME: ${{ secrets.EC2_USERNAME }}
  SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set upt Node.Js
        uses: actions/setup-node@v2
        with:
          node-verison: '20.15.0'

      - name: Install dependencies and build project
        run: |
          cd ${{env.TARGET_PATH}}
          npm install
          npm run build

      - name: Copy file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{env.EC2_HOST}}
          username: ${{env.SSH_USERNAME}}
          key: ${{env.SSH_PRIVATE_KEY}}
          source: "${{env.TARGET_PATH}}/dist/**"
          target: /var/www/lean1123.online/html

      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{env.EC2_HOST}}
          username: ${{env.SSH_USERNAME}}
          key: ${{env.SSH_PRIVATE_KEY}}
          script: |
            sudo systemctl restart nginx
          

          
        
